"""Build src/pages/executive/executive.css from public/perf/legacy.css.

Keeps only the rules that style classes the Executive Dashboard renders and scopes every selector under
`.xd`, so the page looks exactly as it did inside the iframe without the legacy stylesheet leaking into
the rest of the app. Re-run after changing legacy.css:  python3 scripts/scope-legacy-css.py
"""
import re, sys, pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = (ROOT / 'public/perf/legacy.css').read_text()
REACT = (ROOT / 'src/styles.css').read_text()
KEEP = set((ROOT / 'scripts/executive-classes.txt').read_text().split())

def strip_comments(s): return re.sub(r'/\*.*?\*/', '', s, flags=re.S)

def blocks(s):
    """Yield (prelude, body) for each top-level block, bodies kept raw."""
    i, n = 0, len(s)
    while i < n:
        j = s.find('{', i)
        if j < 0: break
        depth, k = 1, j + 1
        while k < n and depth:
            if s[k] == '{': depth += 1
            elif s[k] == '}': depth -= 1
            k += 1
        yield s[i:j].strip(), s[j + 1:k - 1]
        i = k

def classes(sel): return set(re.findall(r'\.([a-zA-Z][\w-]*)', sel))

def scope(sel):
    sel = sel.strip()
    if sel == ':root': return '.xd'
    m = re.match(r'html\[data-mode="?dark"?\]\s*(.*)', sel)
    if m: return ('.xd[data-mode="dark"] ' + m.group(1)).strip()
    if sel.startswith('html') or sel.startswith('#'): return None
    if sel.startswith('body'): return '.xd' + sel[4:]
    return '.xd ' + sel

def rule(prelude, body):
    sels = [x for x in (p.strip() for p in prelude.split(',')) if x]
    keep = [s for s in sels if s == ':root' or (classes(s) and classes(s) <= KEEP)]
    out = [x for x in (scope(s) for s in keep) if x]
    return (',\n'.join(out) + ' {' + body.strip() + '}') if out else None

def walk(s):
    out = []
    for pre, body in blocks(s):
        if pre.startswith('@media') or pre.startswith('@supports'):
            inner = walk(body)
            if inner: out.append(pre + ' {\n' + '\n'.join('  ' + r for r in inner) + '\n}')
        elif pre.startswith('@keyframes'):
            out.append(pre + ' {' + body + '}')
        elif pre.startswith('@'):
            continue
        else:
            r = rule(pre, body)
            if r: out.append(r)
    return out

# Neutralise the React app's own rules for class names both stylesheets use, so only the legacy
# values apply inside the dashboard.
resets = []
for pre, body in blocks(strip_comments(REACT)):
    if pre.startswith('@'): continue
    for sel in (p.strip() for p in pre.split(',')):
        if re.fullmatch(r'\.[a-z][\w-]*', sel) and sel[1:] in KEEP:
            props = sorted({d.split(':')[0].strip() for d in body.split(';') if ':' in d})
            resets.append('.xd ' + sel + ' {' + ' '.join(p + ':revert;' for p in props) + '}')

css = ('/* Generated by scripts/scope-legacy-css.py from public/perf/legacy.css. Do not edit by hand. */\n'
       '.xd { font-family: var(--sans); font-size: 13px; color: var(--ink); -webkit-font-smoothing: antialiased; }\n'
       '.xd a { color: inherit; }\n'
       '/* The dashboard fills the page the way the iframe did: no page padding, full width, legacy paper background. */\n'
       '.page:has(> .xd) { padding: 0; max-width: none; }\n'
       '.page > .xd { max-width: none; min-height: 100%; background: var(--paper); }\n'
       + '\n'.join(resets) + '\n' + '\n'.join(walk(strip_comments(SRC))) + '\n')
dest = ROOT / 'src/pages/executive/executive.css'
dest.parent.mkdir(parents=True, exist_ok=True)
dest.write_text(css)
print(dest, len(css), 'bytes')
